# Generated by Django 3.0.8 on 2020-10-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deliveryboylctn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=30)),
                ('l_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('l_lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(max_length=64)),
                ('order_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('order_lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('deliverd_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
