# Generated by Django 3.0.8 on 2020-10-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryboylctn',
            name='l_lat',
            field=models.DecimalField(decimal_places=7, max_digits=9),
        ),
        migrations.AlterField(
            model_name='deliveryboylctn',
            name='l_lon',
            field=models.DecimalField(decimal_places=7, max_digits=9),
        ),
    ]
