# Generated by Django 3.0.8 on 2020-10-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20201010_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryboylctn',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='deliverd_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
